### ISSUE TITLE
Show dates without leading zeros

### ISSUE THREAD

**Issue by GeoffreyTrang** [openzim/wp1#100]
Welcome to the month of September! Now, I can see that log pages like [Wikipedia:Version 1.0 Editorial Team/Years articles by quality log](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Years_articles_by_quality_log) currently show leading zeros in date headers for the first nine days of a month. Please make the date headers not show leading zeros.

**Comment by audiodude** [comment]
Fixed by #106
