### ISSUE TITLE
Reimplement "custom" tables

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#114]
When I killed the old bot, there was some "custom" table code that went by the wayside. From what I could tell at the time, this code was not used anywhere.

However a user of this code has shown up [on English Wikipedia](https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#User:WP_1.0_bot/Tables/Custom/Roads-1_not_updating). There may be more too.

We should re-evaluate how many users of this code there were and try to recreate the code that creates the custom tables. At the very least, we should get it working for this project.

**Comment by walkerma** [comment]
Do you know a technical way to find out the users of the code?  Or is the a question I should put in my mass message when I've got the list finished? Walkerma

**Comment by audiodude** [comment]
I think that I can figure it out with technical forensics, so to speak.

I think putting out a call for "hey who has a custom table?" is a recipe for everyone to come out of the woodwork and say "Ooooh I had this custom table 4 years ago can I have it again??" and then we have to support a bunch of weird edge cases.

**Comment by audiodude** [comment]
So looking at the old `custom_tables.pl` file, it seems there are simply a number of, as you would expect, custom tables that each have their own code for generating them. The code is here:

https://github.com/openzim/wp1/blob/toolforge/backend/custom_tables.pl

There was a flat file, `Custom.tables.dat` that was used to configure these, including the wikipedia page that they updated and the custom method used to generate the table data. I've uploaded the contents of that file to this gist: https://gist.github.com/audiodude/e099ab2993250cc6e66459eb402c1978

The work involved in resurrecting any of these custom tables is basically:

1. Create a framework for storing the Custom table information, preferably in the database this time, and retrieving it.
2. Create a schema for how to invoke custom python functions based on these definitions, and upload the result to Wikipedia.
3. Integrate the above into the worker jobs. So we need a cron that generates worker jobs for custom tables
4. Actually re-implement the custom logic in Python.

**Comment by audiodude** [comment]
At the very least, the new framework for storing metadata about custom tables should include:

- The user who requested the custom table
- The date at which it was first implemented, and
- A brief description of what it is and what it contains.

**Comment by audiodude** [comment]
Updating with new (buried) code location for custom_tables.pl so I don't have to find it again: 

https://github.com/openzim/wp1/blob/d9f81232603ba9ce37d7ff156325aa6fb3d1d0f0/backend/custom_tables.pl

**Comment by audiodude** [comment]
New requests for this functionality have been filed here: https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Custom_table_updates
