### ISSUE TITLE
wp1.openzim.org does not use HTTP compression

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#126]
* https://wp1.openzim.org https://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly93cDEub3BlbnppbS5vcmc=
* https://api.wp1.openzim.org https://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly9hcGkud3AxLm9wZW56aW0ub3Jn

**Comment by kelson42** [comment]
See also https://github.com/openzim/zimfarm/issues/332 (for the solution)

**Comment by audiodude** [comment]
Check the URLs again:

https://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly93cDEub3BlbnppbS5vcmc=

https://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly9hcGkud3AxLm9wZW56aW0ub3Jn

Compression now verified.
