### ISSUE TITLE
Don't allow user to start a new manual update if one is in progress, even if it's been over an hour

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#186]
Currently there is a "lock" on manual updates, which is the next_update_time, which is set to 60 minutes after the initial update is requested. However, if the rq job is still being processed at that time, we should not allow a new manual update because it will just queue up behind the currently executing one.

**Comment by audiodude** [comment]
Oops, wrong issue.

**Comment by mahakporwal02** [comment]
@audiodude Can I work on this issue?

**Comment by audiodude** [comment]
Yes, thank you!
