### ISSUE TITLE
Shutdown old WP1 engine 1.0

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#193]
Currently, we have completed the following:

- #169 (make links in tables on Wikipedia point to new frontend)
- #180 (put a welcome message on the new tool)

This should mean that some amount of traffic that used to hit the old frontend, from clicking those links, will now hit the new frontend. And editors who wind up on the new frontend page will know where to go to leave feedback and feature requests.

The next possible steps are:

- Put a banner on the old frontend announcing that it is deprecated and that the new one should be used instead. This is a great place to put a "drop dead" date of when we intend to shut down the old frontend completely.
- Redirect traffic from the old frontend to the new one. So if people have bookmarks and go directly to the old frontend, we could intercept them and send them to the new one. This could be implemented some point after the banner is placed on the old frontend but before it is completely shut down. It could be overridden with an "&redirect=0" param which allows the user to stay on the old frontend if they clicked the link in the new welcome banner.
- Actually shut down the old frontend. This could be done by simply turning off the web job on toolforge, so that we could easily turn it back on if something goes wrong. Alternately, if we have redirects from the old frontend to the new one, we could simply remove the redirect=0 param discussed above, so that users are forced to be redirected to the new frontend and the old one functions simply to redirect.

**Comment by kelson42** [comment]
> * Put a banner on the old frontend announcing that it is deprecated and that the new one should be used instead. This is a great place to put a "drop dead" date of when we intend to shut down the old frontend completely.

Yes, ASAP IMO.
 
> * Redirect traffic from the old frontend to the new one. So if people have bookmarks and go directly to the old frontend, we could intercept them and send them to the new one. This could be implemented some point after the banner is placed on the old frontend but before it is completely shut down. It could be overridden with an "&redirect=0" param which allows the user to stay on the old frontend if they clicked the link in the new welcome banner.

Yes, in a month if nobody complains so far.

> * Actually shut down the old frontend. This could be done by simply turning off the web job on toolforge, so that we could easily turn it back on if something goes wrong. Alternately, if we have redirects from the old frontend to the new one, we could simply remove the redirect=0 param discussed above, so that users are forced to be redirected to the new frontend and the old one functions simply to redirect.

Yes, in two months if nobody complains.

@walkerma Sounds good to you?

**Comment by audiodude** [comment]
The banner has been added to the old tool: https://tools.wmflabs.org/enwp10/cgi-bin/table2.fcgi

**Comment by audiodude** [comment]
I started looking into adding a redirect from the old tool to the new one. However, I couldn't immediately figure out an easy way to allow users to override the redirect and use the old tool if they need to.

Basically, I'm trying to implement the redirect at the lighttpd configuration level.

We could add a `?noredirect=1` parameter into the URL, that would cause the redirect to be skipped. However, since the application doesn't know to "persist" this parameter between pages, clicking a link in the old tool would cause the param to get lost and the page to redirect.

**Comment by audiodude** [comment]
So the problem is, a forced, unavoidable redirect from the old tool to the new tool is the same in essence as shutting down the old tool.

**Comment by kelson42** [comment]
I would do an unavoidable redirect and keep the banner on the new to invite people to report problems. If there is a big problem, the we can remove the redirect for the time being needed to fix it. For other bigs, we can fix them on the new engine... But It is perfectly possible that we hear no complain at all.

**Comment by audiodude** [comment]
👍 SGTM

**Comment by kelson42** [comment]
@walkerma @audiodude 15 days left. Can not believe we are almost there :-)

**Comment by audiodude** [comment]
@kelson42 @walkerma I have put in a redirect for all pages from the old tool, to the new tool, and updated the welcome message on the new tool (to no longer say "the old tool is still running"). Let's see if anyone complains in the next week or so, otherwise I consider this task done.

I have also posted a [message on English Wikipedia](https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Old_tool_has_been_shut_down).

Thanks!
