### ISSUE TITLE
User:WP 1.0 bot

### ISSUE THREAD

**Issue by Rosiestep** [openzim/wp1#220]
The bot isn't updating this table (User:WP 1.0 bot/Tables/Project/Women writers) and hasn't been since about July 27, 2020: https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/Project/Women_writers

Thanks in advance.

**Comment by audiodude** [comment]
I don't see any failures in the logs for that project. It looks like someone did a bunch of "manual" updates with the old tool: [1](https://en.wikipedia.org/w/index.php?title=User:WP_1.0_bot/Tables/Project/Women_writers&oldid=970090438) [2](https://en.wikipedia.org/w/index.php?title=User:WP_1.0_bot/Tables/Project/Women_writers&oldid=970091228) [3](https://en.wikipedia.org/w/index.php?title=User:WP_1.0_bot/Tables/Project/Women_writers&oldid=970143231) [4](https://en.wikipedia.org/w/index.php?title=User:WP_1.0_bot/Tables/Project/Women_writers&oldid=970369019)

But in between those, it seems the current bot update the page on July 29, 2020: [5](https://en.wikipedia.org/w/index.php?title=User:WP_1.0_bot/Tables/Project/Women_writers&oldid=970240412)

Let's keep an eye on this for the next couple of days. Thanks for the report!

**Comment by kelson42** [comment]
@Rosiestep I see updates each day since July 27 at https://en.wikipedia.org/w/index.php?title=User:WP_1.0_bot/Tables/Project/Women_writers&action=history.

**Comment by Rosiestep** [comment]
The problem is that the "bot update" is occurring but the statistics aren't changing accurately. I am doing hundreds of article reviews/updates (Importance and/or Quality) each day, but the changes I'm making on the article talkpages aren't reflected in the numbers showing up on the table since July 27.

**Comment by audiodude** [comment]
@Rosiestep can you provide a few examples of articles that you updated/re-classified, just so I know where to look?

**Comment by Rosiestep** [comment]
Thank you in advance, and here you go:

* https://en.wikipedia.org/w/index.php?title=Talk%3ASusan_Chitabanta&type=revision&diff=970054317&oldid=968478741
* https://en.wikipedia.org/w/index.php?title=Talk%3AAnna_Leonowens&type=revision&diff=970069228&oldid=968538679
* https://en.wikipedia.org/w/index.php?title=Talk%3ADian_Fossey&type=revision&diff=970069307&oldid=968536680
* https://en.wikipedia.org/w/index.php?title=Talk%3AKate_Richards_O%27Hare&type=revision&diff=970075348&oldid=968396025
* https://en.wikipedia.org/w/index.php?title=Talk%3AAgnes_Mongan&type=revision&diff=970089035&oldid=968322179
* https://en.wikipedia.org/w/index.php?title=Talk%3AAlma_Lutz&type=revision&diff=970089164&oldid=968322441
* https://en.wikipedia.org/w/index.php?title=Talk%3AThat_Man_in_Our_Lives&type=revision&diff=970054411&oldid=951645502
* Hundreds of other examples in the last 2-3 days in my contribution history here: https://en.wikipedia.org/w/index.php?title=Special:Contributions/Rosiestep&offset=&limit=500&target=Rosiestep

**Comment by audiodude** [comment]
Looking at [the diff](https://en.wikipedia.org/w/index.php?title=User%3AWP_1.0_bot%2FTables%2FProject%2FWomen_writers&type=revision&diff=970743642&oldid=969733045) between today's table update and the one on July 26th, it looks like:

- There have been lots of double digit and triple digit changes.
- Stub/Mid and Stub/Low have gone from 2,296 to 2,397 and 6,723 to 6,857 respectively.
- Stub ??? has dropped from 2,766 to 2,509.
- Overall ??? importance has dropped from 19,164 to 18,494

So if you've rated the importance of about 700 articles (among other changes), these are the results I would expect to see.

Is there something that you've rated that you know is missing from the table? I've spot checked some of the articles you just sent and they all have the proper rating in the WP1 database.

Thanks!

**Comment by Rosiestep** [comment]
Indeed, the August 1st update is an "update". If you look at the diffs between July 27-28, July 28-29, July 29-30, the updates didn't include the changes I'd made. It seems to be okay now. That's what I care about. Thank you!

**Comment by audiodude** [comment]
Thanks for reporting it! Please continue to bugs for any issues you see.
