### ISSUE TITLE
Reduce the number of logins that the worker processes make

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#226]
See [the phabricator bug](https://phabricator.wikimedia.org/T256533) and the [message on my talk page](https://en.wikipedia.org/wiki/User_talk:Audiodude#Important_notice:_You_are_making_a_lot_of_login_requests) for more details.

Basically, every worker task for all 2500+ wikiprojects creates a login, twice actually: once for updating the table and once for updating the logs.

We can use the [pattern here](https://github.com/mwclient/mwclient/issues/256) to login once per update session.

**Comment by kelson42** [comment]
@audiodude Thank you for the quick reaction on this
