### ISSUE TITLE
Frontend: Optimize for mobile viewing

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#236]
There was a report on [English Wikipedia](https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Mobile_view) that some buttons look off when viewed on mobile. We should do a full pass of the frontend app and make sure it works on mobile. Using Bootstrap to begin with should help.

**Comment by Neilblaze** [comment]
@audiodude if this is still up for grabs, I want to take this up! :)
Also can you please share any specific link where the issue is being populated?

For mobile view, I found this issue :-
![openzim](https://user-images.githubusercontent.com/48355572/96904899-573a3280-14b5-11eb-97a6-f778f2e6a317.gif)

**Comment by audiodude** [comment]
@Neilblaze Go for it!

There's no specific link, this issue covers the whole frontend app. It would make sense probably to do it as multiple PRs, one for each page, or even per component.

I'm not sure I understand the issue in the video you provided. Is it that the dropdowns don't provide options at all?

**Comment by audiodude** [comment]
@Neilblaze I've added some more info to the README just now that should help you get up and running with a development frontend server. Let me know if you need more info than that.

**Comment by Neilblaze** [comment]
> @Neilblaze Go for it!
> 
> There's no specific link, this issue covers the whole frontend app. It would make sense probably to do it as multiple PRs, one for each page, or even per component.
> 
> I'm not sure I understand the issue in the video you provided. Is it that the dropdowns don't provide options at all?

No dropdowns are working fine, but there are two issues.

- The dropdowns should either be aligned in a single horizontal line or else we can add a break between the `Quality` & the `Importance`, & keep the respective dropdowns in their adjacent position. I think the first opinion will be good to go!

- The dropdown list is being overflowed for some devices. For me, I've tested both on Apple & Android devices. For Apple, it's working fine but for my Android device, this issue pertains.

**Comment by Neilblaze** [comment]
> @Neilblaze I've added some more info to the README just now that should help you get up and running with a development frontend server. Let me know if you need more info than that.

Thank you very much @audiodude :smiley:

**Comment by audiodude** [comment]
@Neilblaze Any progress on this issue?

**Comment by mahakporwal02** [comment]
@audiodude maybe I could continue with this issue?

**Comment by yashikajotwani12** [comment]
hey !! @audiodude I want to contribute for this , will you please assign me for this . I would begin building then.

**Comment by audiodude** [comment]
@mahakporwal02 @yashikajotwani12 What would each of you do to resolve this issue?

**Comment by mahakporwal02** [comment]
@audiodude Add bootstrap to make the pages responsive, some pages look misaligned and (mis)spaced in the mobile screen view, Make PR for each component (as you said earlier).
