### ISSUE TITLE
Frontend: Need to add ability to compare articles across two different projects, with quality and importance filtering

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#237]
According to the discussion on [English Wikipedia](https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#A_feature_which_I_hope_will_still_be_available_with_the_newest_version_of_this_bot), there is a feature in the old frontend where you can add a "second project" and the site will list all of the articles that overlap in both projects:

https://enwp10.toolforge.org/cgi-bin/list2.fcgi?run=yes&projecta=Women_scientists&namespace=&pagename=&quality=B-Class&importance=Mid-Class&score=&intersect=on&projectb=Women+writers&qualityb=&importanceb=Low-Class&limit=250&offset=1&sorta=Importance&sortb=Quality

This list can be filtered by the quality and importance ratings for either project, and the resulting display shows the rating in each project separately so they can be compared.

Instead of piling this functionality on to the existing article list page, it might make sense to make a separate top level tab with a comparison page where the user can input the project names and the desired quality and importance ratings.

**Comment by audiodude** [comment]
We'll consider this blocking the shutdown of the old tool, so very high priority.

**Comment by kelson42** [comment]
@audiodude OK, important finding indeed.
