### ISSUE TITLE
Measure audience

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#248]
We should link this service with our Matomo instance at https://stats.kiwix.org.

This can be done via:
* A piece a javascript running on each page
* A web log parser calling the matomo online hookd (we have already the piece of code doing that properly).

**Comment by audiodude** [comment]
I would prefer the Javascript, since users need to have Javascript enabled to use the Vue site anyway.

**Comment by kelson42** [comment]
The instructions are given here, should just work:
https://stats.kiwix.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=10

**Comment by audiodude** [comment]
Fixed by #254
