### ISSUE TITLE
Very high login rate!

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#257]
It is a quite old topic (summer 2020) but I have been aware just now about it: our bot (it is not clear to me if this is the old Perl version, the new Python version, or both together) generate a lot (too many?) login requests to the Wikipedia API. See https://phabricator.wikimedia.org/T256533.

An admin complained about it and ask if we could do something to reduce this amount, see https://en.wikipedia.org/wiki/User_talk:Kelson#Important_notice:_You_are_making_a_lot_of_login_requests

Can we reduce it? Do we have a bug somewhere?

**Comment by audiodude** [comment]
This was fixed in #226

**Comment by kelson42** [comment]
@audiodude Perfect, sorry for the burden.
