### ISSUE TITLE
Setup around configuration

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#271]
A few questions/remarks to secure we don't leak the configuration:
* The configuration file template should be different from the real configuration
* The configuration file(s) should be in the `.gitignore` (with all the files which might appear for temporary saving, like the one with `~` for emacs)
* Secure the file is outside the served directory.

**Comment by audiodude** [comment]
> The configuration file template should be different from the real configuration  ✅

> The configuration file(s) should be in the .gitignore (with all the files which might appear for temporary saving, like the one with ~ for emacs)  ✅

> Secure the file is outside the served directory.  ✅
