### ISSUE TITLE
WP1 DB table has to migrated

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#273]
The Wikimedia tech teams requires our DB table to have a different name `s51114__enwp10` (with an additional underscore). They have published a procedure to do so:
https://phabricator.wikimedia.org/T269609#6766433

We have until end of March to do it.

**Comment by kelson42** [comment]
@audiodude Would you be able to run this migration?

**Comment by audiodude** [comment]
Yes I can do it. If I've got it right we should:

1. Announce that the tool will be down for about an hour, scheduled perhaps for this Sunday or the next
2. Shut down the worker and web services on the production box
3. Perform the migration according to the steps in the phabricator ticket
4. Bring the workers and web processes back up
5. Test the website and do a manual update of a single project to make sure everything's working

Does that sound right?

**Comment by kelson42** [comment]
@audiodude Yes, sounds good.

**Comment by audiodude** [comment]
Okay I posted a notice. I'll do the migration next Sunday, Jan 31.

https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Tool_Maintenance%2C_Sunday_January_31

**Comment by kelson42** [comment]
@audiodude What is the status on this ticket. Could we close it?

**Comment by audiodude** [comment]
@kelson42 no I still haven't done the migration! I keep forgetting.

**Comment by audiodude** [comment]
Okay it's done now! It was way easier than I thought it would be. I left behind all the `lucky_` tables from the migration because those can be deleted.
