### ISSUE TITLE
Write more Cypress integration tests

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#280]
Currently we have only [one integration test](https://github.com/openzim/wp1/blob/main/wp1-frontend/cypress/integration/home_page.spec.js), and it just tests that the autocomplete dropdown opens when a search is entered.

We should have more test cases for the basic usage of the app, such as:

- When the user selects an item from the dropdown, the appropriate table is displayed
- That table has the appropriate row and column labels
- Clicking a number in the table brings the user to the appropriate article detail list page

And for the [article table](http://wp1.openzim.org/#/project/Water/articles?quality=Start-Class&importance=High-Class) page:

- It displays the right name for the page that it is (ie "Water articles - High importance / Start quality")
- Custom Pagination works, with the start page and number of items being respected
- Filtering by article name works

I'm not sure we can meaningfully test the manual update page, which is the last major page in the app right now, because in the integration environment we don't have access to Redis or the worker processes.

This is not an exhaustive list and more tests might be useful or necessary. Also if you accept this issue, the tests do not (and likey *should not*) be made all in one giant PR, but rather split up.

**Comment by audiodude** [comment]
Forgot to mention, but since the dev database is static and well known, we don't have to "guess" at any of this. For example, the existing integration test searches for "Water" because we know there is a WikiProject Water in the dev database. We also know the exact number of articles in every class for that project, etc.

**Comment by mahakporwal02** [comment]
@audiodude @kelson42 I have made cypress for
'When the user selects an item from the dropdown, the appropriate table is displayed'
Please have a look at it so that I can make rest of the tests after your approval.

**Comment by mahakporwal02** [comment]
@audiodude Are there more tests that you need me to add?

**Comment by audiodude** [comment]
@mahakporwal02 Any tests that you can think of that I might have missed would be helpful.

**Comment by mahakporwal02** [comment]
@audiodude I think all important tests have been covered.

**Comment by audiodude** [comment]
What about tests for this widget? 
<img width="782" alt="Screen Shot 2021-03-26 at 11 09 21 AM" src="https://user-images.githubusercontent.com/57832/112674948-c5e43900-8e23-11eb-9b4a-be783aab6b82.png">

Also can we/should we test that clicking the article name brings you to the right article on Wikipedia? Or that clicking on the revision or talk links bring you to the right places?

**Comment by audiodude** [comment]
We have no tests for the manual update page. Do we need some?

**Comment by audiodude** [comment]
Closing, we have a good suite of first tests.
