### ISSUE TITLE
Upgrade Python version to 3.9

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#290]
This should simply be a matter of running the Python tests and assuring they pass, then updating the documentation, CI, and the Docker images.

**Comment by DiyaReddy** [comment]
@audiodude Hello,i would like to try this issue.
so do we need to convert the existing files into python 3.9
and make them run on the latest version?
and update all the documents , CI and Docker images?

**Comment by abdulmoiz37** [comment]
Hello@audiodude.I am Looking to Submit the Proposal in GSOC Through Kiwix.org.I Would Like to Contribute to this issue.can i Work on this issue or is someone else Working?

**Comment by audiodude** [comment]
> @audiodude Hello,i would like to try this issue.
> so do we need to convert the existing files into python 3.9
> and make them run on the latest version?
> and update all the documents , CI and Docker images?

There shouldn't be any code changes necessary. If there are, they will be exposed through running the tests. As the issue says, it's mostly a matter of updating docs, CI and the Docker images.

> Hello @audiodude.I am Looking to Submit the Proposal in GSOC Through Kiwix.org. I Would Like to Contribute to this issue. can i Work on this issue or is someone else Working?

@abdulmoiz37 I believe @DiyaReddy was first in line, sorry. There are other issues in the repo you could look at.

**Comment by abdulmoiz37** [comment]
> > @audiodude Hello,i would like to try this issue.
> > so do we need to convert the existing files into python 3.9
> > and make them run on the latest version?
> > and update all the documents , CI and Docker images?
> 
> There shouldn't be any code changes necessary. If there are, they will be exposed through running the tests. As the issue says, it's mostly a matter of updating docs, CI and the Docker images.
> 
> > Hello @audiodude.I am Looking to Submit the Proposal in GSOC Through Kiwix.org. I Would Like to Contribute to this issue. can i Work on this issue or is someone else Working?
> 
> @abdulmoiz37 I believe @DiyaReddy was first in line, sorry. There are other issues in the repo you could look at.

Okay @audiodude :)

**Comment by audiodude** [comment]
@mahakporwal02 Do you want to take this one?

**Comment by mahakporwal02** [comment]
> @mahakporwal02 Do you want to take this one?

Yes, thanks.

**Comment by DiyaReddy** [comment]
I have tested all the files 575 tests run successfully!

**Comment by mahakporwal02** [comment]
@DiyaReddy I checked there are only 209 tests in CI.
Am I missing something?

**Comment by DiyaReddy** [comment]
Yes, and I have tested tests from the source too that is the reasons the count is more!
