### ISSUE TITLE
Manual update progress bar no longer shows at all

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#315]
This is probably a bug from the changes in #284. Go to the manual update page for a small project like: https://wp1.openzim.org/#/update/Syd%20Barrett

Click "Manual Update" and the button disappears (which it should) but the progress bar is not shown.

I think tangentially to this bug we should also file an enhancement for better development infrastructure around this page. That way we could properly test it both in development and CI.

**Comment by audiodude** [comment]
@mahakporwal02 Would you be interested in working on this?

**Comment by audiodude** [comment]
Created development version of manual update flow in #316

**Comment by mahakporwal02** [comment]
@audiodude Sure.
