### ISSUE TITLE
User:WP 1.0 bot/Tables/Project/Women writers isn't updating

### ISSUE THREAD

**Issue by Rosiestep** [openzim/wp1#329]
User:WP 1.0 bot/Tables/Project/Women writers (https://en.wikipedia.org/wiki/User:WP_1.0_bot/Tables/Project/Women_writers) hasn't updated since April 30, 2021. I tried updating it manually but that, too, doesn't work. Thanks for your assistance.

Rosie Stephenson-Goodknight
Visiting Scholar, Northeastern University, Boston
Chair, Affiliations Committee, Wikimedia Foundation
Vice-President, Wikimedia District of Columbia
Co-founder, Women in Red

**Comment by audiodude** [comment]
Yup, looks like the worker processes are down because of a python 3.9 error (from upgrading the project to 3.9). Thanks for reporting, will fix tomorrow morning.

**Comment by audiodude** [comment]
Okay I've deployed the fix for this. Everything should be back to normal at Midnight UTC on May 6, when the bot runs its next scheduled update. I'll be monitoring closely.

Thanks again for reporting!

**Comment by Rosiestep** [comment]
Your fix worked. Thank you!
