### ISSUE TITLE
Seeding our list of "Wikimedia projects"

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#363]
According to #336, part of the workflow is:

> user chooses the Wikimedia projects he wants the list to apply

I've found this list here:

https://meta.wikimedia.org/wiki/Complete_list_of_Wikimedia_projects

Which seems to list everything. However, it's not in a machine-friendly format. Additionally, if the user wanted to create a list for say, the French Wikipedia (fr.wikipedia.org), what should we store in the database for the metadata for that list? That is, what exactly constitutes a "project" in our data model? Is it a domain and a label ('fr.wikipedia.org', 'French Wikipedia') or is it something more.

I suppose this question comes down to with what is required for passing in the zim file, which I'm not familiar with.

Either way, we need to seed our list of projects so we can provide some kind of dropdown or autocomplete, and it needs to be able to be kept up to date somehow.

**Comment by kelson42** [comment]
@audiodude You can rely on https://meta.wikimedia.org/w/api.php?action=help&modules=sitematrix

**Comment by audiodude** [comment]
Thanks Kelson!
