### ISSUE TITLE
Build simple list creation UI

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#367]
Here is a mockup of the simple list creation UI, for #336.

<img width="1201" alt="Screen Shot 2021-06-20 at 2 59 21 PM" src="https://user-images.githubusercontent.com/57832/122689547-470b5c00-d1d8-11eb-8d3b-d9dccfe1bea8.png">

The project list is populated from the endpoint specified in #366. A project must be selected, but should default to en.wikipedia.org.

The list name is required.

The list of articles can contain as few as one entry. The backend will be responsible for validating this list otherwise.

**Comment by kelson42** [comment]
I would recommend to force underscrores, at least in what is saved. It should exactly match the articleId at the wiki.

**Comment by audiodude** [comment]
I was planning on having the backend normalize with underscores as part of the validation process.

**Comment by kelson42** [comment]
Here is a concrete example why the check should be done https://github.com/openzim/mwoffliner/issues/1486

**Comment by audiodude** [comment]
Good example, thanks! I think we should validate on the backend and transform the list to a canonical form. We should also probably not encourage the user to use spaces, so maybe the placeholder can have something more like a list of articles with underscores and such.
