### ISSUE TITLE
Schema for selection metadata in tool database

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#374]
I'm thinking of the following schema for the `selections` table in MariaDB:

| s_id | s_name | s_user_id | s_hash | s_project | s_model | s_region | s_bucket | s_object_key | s_last_generated |
| - | - | - | - | - | - | - | - | - | - |
| INTEGER PRIMARY KEY AUTOINCREMENT | VARBINARY(255) | INTEGER [user.u_id] | VARBINARY(255) | VARBINARY(255) [eg: en.wikipedia.org] | INTEGER(8) [enum] | VARBINARY(255) | VARBINARY(255) | VARBINARY(255) | BINARY(20)

- **s_name**: The name that the user gave for the list.
- **s_user_id**: The id of the user that requested the generation of this selection.
- **s_hash**: I realize that I need a filename for the S3 bucket/redis key for each selection list. I'm thinking of using a salted hash of the database id. I don't want to use the database id directly because they are increasing monotonically from 1, so abusive users could just go to `selections/1.tsv`, `selections/2.tsv` etc and list all of the selections which we don't really want to encourage.
- **s_project**: The project that the list belongs to.
- **s_model**: id for a "model", such as a list builder, that was used to generate this selection. I'm imagining this as kind of a URL like a java package so something like "org.openzim.wp1.simplelist:1" or "com.travisbriggs.funkylist:3" where the data after the colon is the version of the model that was used.
- **s_backend**: I'm also thinking about how we get this working in development, and my best guess is that we have multiple 'backends' that can serve the list data, with a defined interface for "get" and "put" of lists. In development, it can be "redis" (because not all developers will have access to S3), while in production it will be "s3".
- **s_region**: The s3 region that the data is located in. NULL for backend == Redis.
- **s_bucket**: The s3 bucket name. NULL for backend == Redis.
- **s_object_key**: The "path" or object key in s3. If backend == Redis, this is the key in Redis.
- **s_last_generated**: The timestamp of when the data was last generated. Note that this is in the same timestamp format that the rest of the database uses, a binary string of length 20.

Also note the use of VARBINARY instead of VARCHAR, because everything in the enwp10 database uses VARBINARY to avoid using database collation.

This comment will be updated as I think of modifications to the proposed schema.

**Comment by kelson42** [comment]
Sorry to come too late on this, but your are moving quickly forward. Here are a few remarks:
* I don’t really know the rational behind storing selectiions in Redis, for now and in the future this sounds not necessary to me.
* s_hash can just be a random UUID IMO. There is no need to keep a relation with the user list…. 5is is why you save it.
* s_backend, s_region, s_bucket shoukd be IMO not data drivem, but configuration driven. But maybe I misunderstand the requirements, see my first bullet.
* s_object_key seems not necessary to me, why s_hash is not good enough.
* The table is missing a column for the variables to inject in the list model. Shoukd probably be a json type as not all models expect the same variables.

**Comment by audiodude** [comment]
> Sorry to come too late on this, but your are moving quickly forward. Here are a few remarks:
> 
> * I don’t really know the rational behind storing selections in Redis, for now and in the future this sounds not necessary to me.

I originally thought that we wouldn't be able to use the s3-like bucket backend in development, so was planning on storing selections in Redis for development. This turns out not to be true or necessary.

> * s_hash can just be a random UUID IMO. There is no need to keep a relation with the user list…. This is why you save it.

Right, I think we should rename this to s_uuid and not have it actually be a hash.

> * s_backend, s_region, s_bucket should be IMO not data drivem, but configuration driven. But maybe I misunderstand the requirements, see my first bullet.

My thought here was that, if the configuration of the site changed while it was running, you could have some selections stored in one bucket/region and others stored in a different one. If we know we will never change the backend storage (or we know we will complete a thorough migration of all objects if we ever do) then I agree this is not necessary.

> * s_object_key seems not necessary to me, why s_hash is not good enough?

The s_object_key captures both the uuid and the mechanism used to generate the actual object key. So if we one day decided that the path would be different, we wouldn't necessarily have to migrate all of the objects. In practice, it might be simpler to leave this out and do a migration if we change the object_key schema.

> * The table is missing a column for the variables to inject in the list model. Should probably be a json type as not all models expect the same variables.

Now that I'm thinking of "selections" and "lists" as different concepts, there's the possibility that we could store these separately in a normalized fashion. So we would have potentially multiple selections that were generated from the same list at different times, with all but the most recent waiting to get "cleaned up" by some kind of job.

> * In [3 differents concepts and storage backends #370](https://github.com/openzim/wp1/issues/370) I attempted to set a vocabulary about the concepts, here is seems not respected or there a conceptual mixup beetween list and selection. It seems this table is conceived to store a list… but actually the table is called “selections”. I don’t care much is my proposal of vocabulary is respected, but we should agree clearly on a way to name things.

Right, as acknowledged in the other comment and earlier in this one, I didn't appreciate the distinction between lists and selections. I think that distinction is valuable and we should respect it going forward.

**Comment by kelson42** [comment]
Thx for agreeing on most of my remarks. Therefore I don't have much to add. Just:
* About S3, is see this like a DB, and you seem to understand the rational behing my thoughts properly, Regarding s_object_key, can be configuration or event staticly code driven
* Regarding the 1 to n relationship beetween list and selections. This is obviously not wrong. But I'm not event sure we need it as IMO we don't care about older selections. At least for the moment. And this is true hat if go with only one selection per list, then having everything in the same table is not that chocking anymore... Not sure what is the best here... maybe keeping two different tables is still the most healthy approach in any case!

@rgaudin Any thougths?

**Comment by audiodude** [comment]
I think one immediate advantage to have selections be separate from builders/lists is that one of the CUJs specifies that the user should be able to download the selection in XLS format. I was imagining that we would store XLS and TSV separately in the storage backend, and thus we would have at least two entries for each list builder based on content type.
