### ISSUE TITLE
Stop adding "<project> articles by quality" category to "<project> articles by quality log" pages

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#392]
The bot creates logs like this one for the [Cultural Heritage of Serbia](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Cultural_Heritage_of_Serbia_articles_by_quality_log).

In the process, it adds that log page to the [Category:Roman military history articles by quality](https://en.wikipedia.org/w/index.php?title=Category:Roman_military_history_articles_by_quality&action=edit&redlink=1)

However in [many cases (see discussion on English Wikipedia)](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Roman_military_history_articles_by_quality_log) this is not desired. The project is defunct, and the category should be deleted.

In practice, adding these pages to an empty category seems to result in the category being created anew, which frustrates the efforts of editors who seek to delete these categories. It also may contribute to the circumstance that a project can never be "deleted" in WP 1.0 Bot, because the bot will always see the "<project> articles by quality" category and create a new project for <project>.

We should simply stop adding the "... by quality" categories to log pages.

**Comment by kelson42** [comment]
> In the process, it adds that log page to the [Category:Roman military history articles by quality](https://en.wikipedia.org/w/index.php?title=Category:Roman_military_history_articles_by_quality&action=edit&redlink=1)

@audiodude This category doesn't exist anymore since 5 years! You mean an other one I guess?

**Comment by kelson42** [comment]
@audiodude I'm a bit worried about this (kind of) bug because it seems to "drive crazy" editors. It is not good for the WP1 project "karma". Any chance that it could be quickly fixed?
