### ISSUE TITLE
List creation error displayed appropriately on the frontend

### ISSUE THREAD

**Issue by mahakporwal02** [openzim/wp1#399]
The error message displayed on entering forbidden characters aka ["#", "<", ">", "[", "]", "{", "}", "|"] in the `items` form field in http://wp1.openzim.org/#/selection/lists/simple/new is incorrect because the the API fields are wrong and they have changed their meaning. Request being sent from `CreateSimpleList` to `/selection/user` should be edited.

**Comment by audiodude** [comment]
This is for error display.

**Comment by audiodude** [comment]
@mahakporwal02 Please update this issue with a description of the problem (the API fields are wrong and they have changed their meaning) and possibly the proposed solution.
