### ISSUE TITLE
Does not find "Knots"

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1#424]
It's all in the title. There's a [Wikiproject Knots](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Knots), but the tool does not seem able to retrieve articles from that project (does not appear on the project list)
![image](https://user-images.githubusercontent.com/21675885/130405881-f63f3680-938b-4be7-a153-d86ea531d7a0.png)

**Comment by kelson42** [comment]
Probably the project "Knots" does not have asked to get the WP1 bot going through its articles.

**Comment by Popolechien** [comment]
Looks like the project isn't listed by the WP1 project on WP.
