### ISSUE TITLE
One should be able to populate items in the manual selection tool directly from a project identified in the "project" tab

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1#426]
At this stage I do not know how I can generate a list of items, unless I copy/paste each article by hand (unpractical).

If it is, in fact, possible, then this should be listed along with the examples e.g. 
Eiffel_Tower
Statue_of_Liberty
Wikiproject_dogs

**Comment by kelson42** [comment]
The custom list is a manually defined list. This is the thing we need for many of our partners. A feature, not a bug. Automatically generated will come later.

**Comment by Popolechien** [comment]
> This is the thing we need for many of our partners.

Please describe the use case because as far as I know _my_ partners are looking to generate zim files with the least possible effort and this tool does not allow for this.
