### ISSUE TITLE
Too much information presented is entirely irrelevant

### ISSUE THREAD

**Issue by Popolechien** [openzim/wp1#429]
There is so much information presented in each table that it amounts to glorified clutter.
![image](https://user-images.githubusercontent.com/21675885/130408693-ddd819cd-c922-4fbd-b2c1-09192040d6fb.png)

Articles probably do not need a link to the talk or history pages but I can understand it follows local Wiki custom to present them as such.
More importantly we have no indication as to what the dates given mean. Are these permalinks to when articles were given a certain status? Something else? What is the purpose of these? How is it actionable?

**Comment by kelson42** [comment]
The problem here IMO is that you don't do the QA of a Wikiproject.

You need a link to the talk page if you want to re-evaluate it.

We would benefit of a table header yes. If we agree on this, I would recommend to open a dedicated ticket.

**Comment by kelson42** [comment]
Closing, can bevreopen if more feedback in that direction from actual users.
