### ISSUE TITLE
List selections in a form of a table

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#433]
Would be better IMO to have the table like in an sheet, something doable easily with https://datatables.net/.

**Comment by audiodude** [comment]
I disagree. I don't think having the list as a table is useful, since there is only one column. Having it in a textarea makes it easily editable, selectable, and copy/pasteable.

**Comment by kelson42** [comment]
@audiodude It seems to me there is a misunderstanding, this ticket is about the list of selections, not about the list of article titles.

**Comment by audiodude** [comment]
Ah okay.

The only problem with having the selections in the form of a table is that there can be N rows for each builder, one for each selection. But I'm sure we could do something with rowspan or something.

**Comment by kelson42** [comment]
To start, I would just make one row per selection/list with for example the following columns:
* name of the selection
* builder id
* creation date
* last update date
* last generation date
* update button/icon
* delete button/icon
* download tsv button/icon

**Comment by audiodude** [comment]
I'm not sure the builder id is relevant. Do you also suggest getting rid of the URL copy functionality?

**Comment by audiodude** [comment]
I assume we would also want a "delete" button/icon per #431?

**Comment by kelson42** [comment]
Not sure, kind of assume that users are skilled enough to make mouse right click and copy link... but might be wrong. That said, most of the users won't even need to do so... They will just download the TSV.

**Comment by kelson42** [comment]
For the delete button, i believe it might be better to make it available in the edit mode to avoid any confusion and click by error.

**Comment by audiodude** [comment]
I've started recreating #437 in a clean branch. I tried using datatables, but it doesn't work with Vue because Vue rewrites the DOM at will and the data stylings won't stick.

**Comment by audiodude** [comment]
Though maybe I can re-apply the datatables treatment when the data actually changes?

**Comment by kelson42** [comment]
@audiodude I would recommend to do what ever is necessary to implement the ticket in a superseeding PR.
