### ISSUE TITLE
Think about how to make a comment

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#435]
I think it will be soon necessary to allow to put a comment in a list. This could be necessary for a user or even the WP1 engine. The challenge is that "how?" because we need a formating rule which secure there won't be no conflict with a potential article.

**Comment by audiodude** [comment]
I think we can use shell style comments, lines starting with `#`, because the number sign is not a valid character in article names. Something like:

```
# Here are some articles:
Eiffel_Tower
Statue_of_Liberty

# I especially like these, but
# let me know what you think about them.
Barack_Obama
President_of_the_United_States
```

We can pre-process the list to remove the comments and the empty lines when "materializing" to a selection.

**Comment by kelson42** [comment]
Sure about the number sign? Look at https://en.wikipedia.org/w/index.php?title=%EF%BC%83MeToo&redirect=no for example!

**Comment by audiodude** [comment]
Yes. Notice that the URL that you linked has the "#" URL encoded. It is not possible to reference the name of that article any other way. Also, I'm going off the reference here: https://en.wikipedia.org/wiki/Wikipedia:Article_titles#Special_characters

**Comment by kelson42** [comment]
It is encoded in the URL (normal) but not in the articleID in the DB probably... and not in our list.

**Comment by audiodude** [comment]
Right now, the list validation will not let you put number signs in list items, based on the reference I cited.

**Comment by kelson42** [comment]
Ok, then perfect to me :) Quite happy the solution is that simple. Already spent a bit of time today thinking about an alternative because assuming the # character would not work.
