### ISSUE TITLE
Reports about bad/wrong articles

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#436]
We need a way to report/act on wrong articles.

We could:
* Comment wrong articles
* Include them anyway in the selection
* Rremove them automatically from the selection

What even happen we should report about them somehow. For the moment I see nothing looking like such a report.

**Comment by Popolechien** [comment]
Can confirm: I created a list where one of the entries had an obvious typo which would return no article whatsoever, but did not get a notification.

**Comment by audiodude** [comment]
Is this a duplicate of #373?

**Comment by kelson42** [comment]
Yes
