### ISSUE TITLE
Lots of npm deprecation warnings when building the app

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#452]
Should look into these, lest it stop working suddenly.

**Comment by kelson42** [comment]
@audiodude Still valid?! Current dependabot is empty!

**Comment by audiodude** [comment]
I was talking about deprecation warnings, like "nodefoo 1.12 is deprecated and will stop working! Please upgrade to nodefoo 2.0". However these seem to have gone away due to upgrading to Vite in #540. Closing.
