### ISSUE TITLE
Backup WP1

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#454]
We should backup the database, we start to have too many sensitive data in it.

We have standard way of doing so at Kiwix, but I'm unsure about what exactly (files, dbs, etc....) should be backed-up.

**Comment by kelson42** [comment]
@audiodude Would you be able please to make a list of assets we should periodically backup.

**Comment by audiodude** [comment]
@kelson42 The only meaningful data the WP1 site stores is in the `s51114__enwp10` database on Toolforge. I assume this database is regularly backed up independently of anything we do, but I don't know for sure.

The Redis instance only stores ephemeral data like job queues and progress counts.

Obviously with the new selections data, we are storing materialized selections on AWS S3, but people don't usually talk about backing up data stored there.

**Comment by audiodude** [comment]
Looks like they have a primary-replica setup, but they don't do offsite backups. They recommend mysqldump.

https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#ToolsDB_Backups_and_Replication

**Comment by kelson42** [comment]
@audiodude @rgaudin IMO we should add our backup companion to backup mysql DB "s51114__enwp10".

**Comment by kelson42** [comment]
@rgaudin Thank you! What are the rationals to not putting it in the `docker-compose.yml`, with best will, I hardly can find one :(

**Comment by rgaudin** [comment]
- the database is not defined in the compose. It's hosted on a different system within wikimédia cloud. No reason to include a backup of something not in the recipe.
- the compose is a somewhat generic recipe of wp1 deployment. Backup is not required nor involved in running wp1. It's specific to our deployment.

**Comment by audiodude** [comment]
I agree. If, for example, you went to deploy the WP1 server and the backup image process failed to start, would you consider that a failure of WP1 deployment?

**Comment by audiodude** [comment]
btw, thank you @rgaudin !

**Comment by kelson42** [comment]
@rgaudin the DB engine is not provided by us only for legacy reason (this tools was first on toolserver and then toolforge which was/is a shared/limited infrastructure)... and actually we are OK continuing like this because it makes on service less to take care.

@audiodude For the rest the backup should be a *required* piece of infrastructure. If a backup system does not work properly, the whole production operation is in danger.

Without being in the docker-compose:
* We might hardly/know and understand how it works (this ticket seems the only documentation)
* If it stops to run, which might easily happen without being in the `docker-compose.yml`, the only "security" we have that we are triggered is that borgbase will send us an email notification (this is pretty fragile IMO).

To conclude: I have looks like quite difficulties to follow the rationals of not having it in the `docker-compose.yml`, we might have to rediscuss this.

**Comment by audiodude** [comment]
If we consider backup to be a critical part of a functioning system, then you've answered my concern and I _do_ agree that it should be in docker-compose. It should be trivial to add a few lines to docker-compose based on the docker run line that @rgaudin provided.
