### ISSUE TITLE
[URGENT] Move server to debian-11.0-bullseye 

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#461]
We have currently a debian-10.0-buster.

**Comment by kelson42** [comment]
We need to keep our infra up2date and on the top of this, Wikimedia requires us to do it befure June 2022.

What I could propose is:
* Keep this system running
* Create a new instance 
* During a WE make the move
* Delete the old instance

**Comment by audiodude** [comment]
As far as I understand, we don't actually have anything running on the toolforge instance. The only thing running there is the "old" web app, which is currently just a redirect to wp1.openzim.org. If we let it get deleted, it would just mean that the redirect stops working.

We could even put a notice on the old web tool that says "This URL will stop working after June 1, 2022. Please update your bookmarks to wp1.openzim.org before then" and then wait 5 seconds to redirect. But I'm not sure that's really necessary.

The wp1 updater jobs did run on the Stretch Grid Engine, but those have long since been migrated to the wp1 box Python cron jobs.

**Comment by audiodude** [comment]
To put it another way, I'm not sure there's anything to be migrated, and I'm not sure it's necessary to install a new "web app" on Debian Buster that just redirects to the new wp1 web app.

**Comment by kelson42** [comment]
@audiodude We maybe have two problems: one with toolforge and one with VPS, but both about deprecated OSes.

See https://phabricator.wikimedia.org/T306082

We don't have a lot of time.

@audiodude I would be ready to setup a new VPS box to allow you to move smoothly to a new infra. Would that be OK? I think it would be good as well to create a phabricator to remove our toolforge account, what do you think?

**Comment by audiodude** [comment]
@kelson42 Okay I understand better.

If you want to set up a new VPS box, I would be happy to SCP over the config files and run the production install. We would also need to change the DNS of wp1.openzim.org once the new box is up and running.

I can file a phabricator task to shut down our toolforge account, as long as that doesn't mean we lose access to the toolforge db.

**Comment by kelson42** [comment]
@audiodude I have created a new VM instance called `mwcurator` to replace `wp1`. Unfortunatly, there is still a problem with the external volume. I have assigned you the Phabricator ticket as beside the volume stuff, I guess the work will be on you.

Concerning the toolforge account, I'm in favour now to delete it. We migrated to VPS 3 years ago (already!), therefore I guess that if we needed still something on this box we would have already migrated it. Consequently, If you feel confortable with this, please open a ticket like you propose to request its deletion (and subscribe me or put the link to the ticket here).

**Comment by audiodude** [comment]
@kelson42 So I assume I should follow the phabricator task and wait for the volume issues to be resolved, then migrate over the wp1 stack?

I don't think we can delete our toolforge account, because my impression of the docs is that a toolforge account is required for replica and application database access, which we are definitely still using. I'm not 100% sure though.

**Comment by kelson42** [comment]
@audiodude Yes, I will ping you as soon as I have created the volume and made it available to the new `mwcurator` instance.

For the Toolforge, I you might be right or not... I'm really overasked here. Maybe this is worth a ticket just to ask. IMO would be better to have a clean situation and not leave our old stuff (at least the files) just somewhere lon Toolforge ike this.

**Comment by kelson42** [comment]
@audiodude Finally the volume is there and mounted on `/data`. I'm migrated the data for `wp1_selection_stuff` and will take part of that part. So you can move your stuff

**Comment by kelson42** [comment]
@audiodude I have installed `docker` and it is ready to go. In addition, I have migrated the data+container of `wp1_selection_tools` to `mwcurator`. I'm testing if it works accurately, but so far so good. As a consequence from my side, "my stuff" is migrated.

**Comment by kelson42** [comment]
@audiodude I recommend to put the maximum of interesting stuff (like the git repo for example) in `/data`. Doing so, next time we have to change the VM, we will just have to attache the external volume to the new VM and no much work would be then left to do.

**Comment by audiodude** [comment]
@kelson42 I've moved the necessary directories to the mwcurator /data/ directory and I've verified that I can run the bot and the web interface successfully. What's left is moving wp1.openzim.org DNS to point to the new IP address, but I can neither find that address, nor do I know how to point openzim.org addresses. Any help would be appreciated, thanks!

**Comment by kelson42** [comment]
@audiodude Great, this is a floating IP. Do you want me to make it point to the new server NOW?

**Comment by audiodude** [comment]
@kelson42 yeah if you're available do it now, I'll hop on Slack to coordinate and we can roll back if there's problems.
