### ISSUE TITLE
Research whether ZimIt is an appropriate Zimfarm for Wikipedia On Demand

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#480]

**Comment by rgaudin** [comment]
The best option, at least for now would be to use the [youzimit farm](https://farm.youzim.it/pipeline/filter-todo) that is used by youzim.it.

We'll use one of the worker machine hosted by the foundation and currently working on openZIM farm. It will accepted task from two different APIs (this is already supported).

Only *issue* I can see at the moment is that the `ZIM_UPLOAD_URI` is a single farm-api-wide environ at the moment. So we'll upload those ZIMs to the zimit bucket (albeit using a different warehouse_path) for now. Maybe we'll add a way to change it in the zimfarm later on.

**Comment by audiodude** [comment]
Okay it sounds like youzimit is the way to go. Since this is just a research task, I'm marking it as complete.
