### ISSUE TITLE
The Zimfarm form must contain any additional metadata that is required for the ZIM file

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#482]

**Comment by rgaudin** [comment]
See https://github.com/openzim/zimfarm/blob/master/dispatcher/backend/src/common/schemas/offliners/mwoffliner.py

**Comment by kelson42** [comment]
UI should be as simple as possible, we should really do only what is mandatory and offer a formular only if a metadata can not be automatically computed/given.

**Comment by audiodude** [comment]
How do we know which of those fields is required?

**Comment by rgaudin** [comment]
look for required=True

**Comment by audiodude** [comment]
From discussion on slack:

> Meta data `Description` and `LongDescription` should be given, see https://wiki.openzim.org/wiki/Metadata to check which metadata should be given

**Comment by kelson42** [comment]
@audiodude What is mandatory is explain on wiki.openzim.org, assuming everything is clear here. Otherwise please asking.
