### ISSUE TITLE
The Zimfarm form should be able to be submitted to the backend API of the Zimfarm installation to create a ZIM file

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#483]

**Comment by rgaudin** [comment]
This would be done easily using the [zimfarm API](https://api.farm.openzim.org/v1#/restricted/addRequestedTask).

I suggest following an approach similar to what the zimit-frontend (youzim.it) does: create a unique schedule, request a task for it, delete the schedule.

https://github.com/openzim/zimit-frontend/blob/main/api/src/routes/requests.py#L44

For this, you would need:
- an endpoint (#480)
- an API Token
- an agreed-upon resource profile (cpu, mem, disk) for those tasks (TBD)
- S3 bucket and access for uploads
- maybe mailgun credentials if you intend to use email

**Comment by audiodude** [comment]
The API Token makes sense, I assume we would set one up and I would include it in every request.

How are the S3 bucket/mailgun credentials specified? Do they need to be set up in the youzimit project? Is that what you referred to in #480, that there's only one `ZIM_UPLOAD_URI`?

**Comment by rgaudin** [comment]
Given the token expires after some time, it's best you store the username/password and re-request a token when needed.
There's an example of how to do it at https://github.com/openzim/zimit-frontend/blob/main/api/src/zimfarm.py
You may actually consider reusing that module altogether.

As for S3, you should not need it unless you plan on uploading additional files as ZIM files will be directly uploaded to it (yes, on the zimit bucket).

For mailgun, we'd need to create a sender and configure it on the DNS records then eventually create the token. Let me know if you'll need to send emails and if so, what would be the sending domain (`wp1.openzim.org`?)
