### ISSUE TITLE
Unable to edit large selections

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#503]
Here is my list of selections:
![image](https://user-images.githubusercontent.com/1029718/187061077-1413d9c2-3734-4158-95e6-ad9b3401c475.png)

See on the pointer and the url in the bottom left corner.

Then when I click on the "Edit" button I get:
![image](https://user-images.githubusercontent.com/1029718/187061106-ee6c7257-54ce-4470-860a-ecf1f85856bd.png)

I would like to edit my list instead of this 404 error (which actually should be a `403 Forbidden` error, see #502)

Remark: My other test list seems to be right. Surprisingly. I suspect that somehow this is linked to the size of the selection. The "Solarspell" has many thousands entries.

Remark2: What is strange as well, it seems that WP1 has not been able to generate a list for this selection. There is no download link available. An other problem probably related.

**Comment by audiodude** [comment]
Yes, it's probably related to the size of the builder. We have never tested the system on actual Simple builders with thousands of selections as you described. If there is some kind of error in the database, the retrieval method is probably returning `None` which the frontend interprets as 404.

**Comment by kelson42** [comment]
Lets see what is the root cause, but this kind of size is normal. Here are the lists which are currently stored in git which could/should be mixed in the WP1 selection tool https://download.openzim.org/wp1/enwiki_2022-08/customs/.

**Comment by kelson42** [comment]
@audiodude Any clue about the root cause of the bug?

**Comment by audiodude** [comment]
Yes. The data is stored as JSON in a BLOB column, but the maximum size of such a datatype is 65,535 bytes (64 K) so the data gets truncated and the resulting JSON is likely invalid.

The fix is to store as either MEDIUMBLOB (16 MB) or LONGBLOB (4 GB). I believe LONGBLOB is the better choice because as far as I know the only overhead is an extra bit to store the length value, which should be inconsequential. However with 4 GB of storage available in the database, we do expose ourselves to the risk of an abuse vector where users could store arbitrary data posing as simple lists. This could be mitigated by limiting the document size at the application layer.

**Comment by audiodude** [comment]
Also once the database is migrated and the datatype is fixed, the previous data will remain truncated and be unrecoverable of course. Don't know whether you would prefer to "auto delete" this junk or handle it somehow in the web server with a 500 response and a message of "Sorry, your selection was found but the data was not retrievable"

**Comment by kelson42** [comment]
@audiodude yes, LONGBLOB, but maybe it would be good to have a kind of artificial and configurable maximum sixe. You can remove the broken entry.

**Comment by kelson42** [comment]
@audiodude Is the patch rolled out? Because I have tested again with https://github.com/openzim/wp1_selection_tools/blob/master/customs/solarspell/wikipedia-for-schools_en.tsv and it fails, see https://wp1.openzim.org/#/selections/simple/31

**Comment by audiodude** [comment]
I deployed the fix just now. It wasn't deployed immediately because the WP1 bot was in the middle of its update (it happens from 0:00 - 8:00 UTC daily).

Seems like we need some way of coordinating releases, since this has happened before.

**Comment by kelson42** [comment]
> Seems like we need some way of coordinating releases, since this has happened before.

Yes, would that be possible to close the ticket only when deployed.

**Comment by audiodude** [comment]
> Yes, would that be possible to close the ticket only when deployed.

The problem with that is it messes up the github workflow of putting "Fixes #xyz" in the PR

**Comment by kelson42** [comment]
@audiodude You are right, I forgot about that detail. Maybe we could link the slack channel so each time a bug is fixed and when a service is restarted, 5en we get a notification on Slack.
