### ISSUE TITLE
Use openZIM formatting

### ISSUE THREAD

**Issue by rgaudin** [openzim/wp1#518]
I know this is mostly a single-person repo but for the maintenance's sake, harmonizing with the rest of the openZIM codebase would be nice.

- [black](https://pypi.org/project/black/)
- [isort](https://pypi.org/project/isort/) (using `--profile black`)
- [flake8](https://pypi.org/project/flake8/) (with `max-line-length = 88` to match black)

[Sample workflow](https://github.com/openzim/wikihow/blob/main/.github/workflows/qa.yml)

**Comment by audiodude** [comment]
Sigh. The thing I hate about black is it's main feature: it's not configurable. I know that pep8 recommends 4 spaces for indents, but I'm so used to 2 now after working at Google. Code with 4 spaces would be hard for me to read.

Same thing with isort. The standard Google import order is 1) standard libs, alpha sorted 2) library references (like `pymysql`) alpha sorted, then finally 3) local library code, alpha sorted (all separated by one newline). This is what I'm used to reading and whatever isort wants to do is probably just going to mess up readability for me.

As you mentioned, I'm the only maintainer actively working on this codebase. I'm not sure it's worth those headaches just to align with the rest of openzim.

**Comment by rgaudin** [comment]
Fine with me then.

**Comment by audiodude** [comment]
Thanks. And to be clear, we do have auto-formatting with `yapf` with pre-commit checks, but thanks for pointing out the workflow, I'll add that too (I noticed with our GSoC student that they weren't running pre-commit and code got merged that wasn't formatted).
