### ISSUE TITLE
SPARQL materialization for projects other than en.wikipedia.org

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#520]
The SPARQL selection creation form has a dropdown of Wikimedia projects, borrowed from the Simple selection dropdown. However, this selection is not respected and results are hardcoded to come from en.wikipedia.org. We should make this selection matter (it is already plumbed through the builder code).

**Comment by audiodude** [comment]
The list of projects that is supported by the Wikidata Query Service is here: https://noc.wikimedia.org/conf/dblists/categories-rdf.dblist

We should cross reference this list to our list of projects (for example, `ltwiki` probably refers to our project `lt.wikipedia.org`) and limit the selection to projects that are available.

**Comment by audiodude** [comment]
Actually that information was taken from https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Categories which is describing the "category service" and its limited support for select wikis. It's not clear which projects in general are included in Wikidata Query Service.

**Comment by kelson42** [comment]
> It's not clear which projects in general are included in Wikidata Query Service.

Worried about that, it seems we might need an upstream ticket here. It shoudl be clear.

**Comment by audiodude** [comment]
I think the general schema of Wikidata is that it has abstract "entities" that are not tied to any particular Wikimedia project. Some entities have articles in en.wikipedia.org, some have articles in fr.wikipedia.org, some have articles in both and some have articles in neither (I know I've personally encountered plenty of QID entities in Wikidata that don't have a corresponding article in any wiki).

Even my queries that were limited to en.wikipedia.org, like the "bands starting with M" sample query, returns results for bands that Wikidata knows exist but don't have an article in english wikipedia. The WP1 backend currently automatically ignores such things.

So I think the best we can do is filter by the project that the user indicates, and if there is no item in that project for certain entities, they will simply be filtered out.

**Comment by kelson42** [comment]
> I think the general schema of Wikidata is that it has abstract "entities" that are not tied to any particular Wikimedia project. Some entities have articles in en.wikipedia.org, some have articles in fr.wikipedia.org, some have articles in both and some have articles in neither (I know I've personally encountered plenty of QID entities in Wikidata that don't have a corresponding article in any wiki).

Obviously. See for example https://www.wikidata.org/wiki/Q105046994 (libkiwix)

> Even my queries that were limited to en.wikipedia.org, like the "bands starting with M" sample query, returns results for bands that Wikidata knows exist but don't have an article in english wikipedia. The WP1 backend currently automatically ignores such things.

Pretty logical indeed.

> So I think the best we can do is filter by the project that the user indicates, and if there is no item in that project for certain entities, they will simply be filtered out.

Yes, but I don't understand how this comment helps with the problem reported first. Does the selectbox is OK? Does your latest PR fix the problem and select articles in the Wikipedia chosen in selectbox in WP1?

**Comment by audiodude** [comment]
Yes the attached PR fixes the problem. There was no problem with the select box, it was added for the "simple" selection and remains valid in the SPARQL context.
