### ISSUE TITLE
Make sure docker-compose runs on production machine on reboot

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#579]
In rare instances, the Wikimedia VPS team might need to restart our machine. We should make sure that `docker-compose up -d` or an equivalent command is run on system startup, that way our services come back automatically after a restart.

**Comment by kelson42** [comment]
AFAIK this is a flag at the container level to be set (via the yml file for docker compose). As long as Docker daemon is started, it should work.

**Comment by audiodude** [comment]
Yes I believe it's already set up properly, the real problem was that the instance didn't come up cleanly.
