### ISSUE TITLE
Stop Zimfarm polling after some timeout

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#608]
As written, ZIM file polling for the completed file set will continue indefinitely. This could be a problem if there's some unforeseen error in the process and the files will never be ready. We should quit after some set time, maybe 2 hours?

**Comment by kelson42** [comment]
@audiodude I don't think this is a good idea. As long as the task is on the pending list it should wait. Maybe the Zimfarm is to slow, but this is an other problem. If the ZIM file is generated the API tells you and you should act accordingly. Not sure to understand what problem do you try to fix exactly?

**Comment by audiodude** [comment]
See comment in https://github.com/openzim/wp1/pull/611#issuecomment-1521145745

Perhaps the term "polling" is confusing. We have a webhook for the task to be `ended`, but as far as I understand there is no webhook for "ZIM file ready in S3". That's what we're polling for. See comment above.

**Comment by rgaudin** [comment]
I proposed somewhere (slack?) that we extend the webhook to support file events (created, uploaded)

Currently, only events that changes the status of a task triggers a webhook call. We have no ticket on zimfarm ATM.
