### ISSUE TITLE
Save Selection ZIM description/long description in the database

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#610]
Currently, when the user enters a Description/Long Description, we don't save it anywhere. We simply add it to the ZIM file request and that's that.

However, if there is an error on the Zimfarm side and the user wishes to retry, it would be nice to pre-fill the required fields with their previously entered data. To do this, we need to save that data in the database.

**Comment by kelson42** [comment]
I’m supportive of the idea

**Comment by audiodude** [comment]
Fixed in #616 and #617
