### ISSUE TITLE
Refactor ZIM files into their own table

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#612]
Based on the requirements in #581 and #610, we should refactor the ZIM file data into its own table, rather than being columns on the Selection table. This is because when the Builder is updated and a new Selection is generated, we want to maintain the link to the old ZIM file task/URL while we re-generate a new one. We also need a place to store `description` and `long_description` for the ZIM file, which we need to re-provide on error cases and when generating a new ZIM. It seems awkward to store that data in the Selection table.

**Comment by kelson42** [comment]
@audiodude Sounds logical indeed.
