### ISSUE TITLE
pytest 'resource' module not found 

### ISSUE THREAD

**Issue by logan-keede** [openzim/wp1#713]
![image](https://github.com/openzim/wp1/assets/68557630/030845df-03ff-40ac-9bef-8f763c49769c)

**Comment by audiodude** [comment]
This seems to be https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource

No one has ever attempted to develop wp1 on Windows before.

**Comment by logan-keede** [comment]
It seems all my problem arise from the fact that I was trying to install this on Windows, I will try installation on Linux let you know if I face any problems. There is a bit of confusion in **credentials.py.dev** but i am assuming i just need to copy from **credentials.py.dev.example** and add key, secret in STORAGE for which i need to contact @kelson42 and get a developer account in zimfarm, (or is there an other way?), what is the relevance of **replica.my.conf** mentioned in Readme.md? is it strictly needed for installation? if so, how?
