### ISSUE TITLE
wp1_openzim website not giving me zim download link

### ISSUE THREAD

**Issue by hamoudak** [openzim/wp1#717]
hi everyone

this is my first to use the wp1 website, and I think I have made everything right according to the docs;  when i need to create a zim file of my selections, the spinner keeps loading for very long time for no reason . I  have waited about one day for every file i requested with no success.  I don't know what's wrong !

on this screen just a list for one page called Tajine.
https://en.wikipedia.org/wiki/Tajine

![wp1 openzim org_](https://github.com/openzim/wp1/assets/155604457/5190bcab-fb9f-40e4-a8bf-527e120fee59)

and I have a list as you see it below .
<img width="960" alt="Untitled" src="https://github.com/openzim/wp1/assets/155604457/e79e6bf6-badc-491b-b83b-98793fba12f6">

**Comment by audiodude** [comment]
It looks like the server that creates the ZIM file seems to have stalled somehow. We're looking into it, thanks for the bug report!

**Comment by hamoudak** [comment]
I appreciate your quick reply. I hope it will be fixed .

**Comment by rgaudin** [comment]
It's an issue with others tasks not ending properly, keeping the slots for themselves. People in charge of this have been informed. Thanks for reporting.

**Comment by hamoudak** [comment]
thanks for your explanation; am gonna try later.

**Comment by hamoudak** [comment]
worked for me in the last two days ; and I want to add a note : 
the wikimedia cookbook list won't work as image shown above . you should add "cookbook" , like that Cookbook:Damper_(Australian_Campfire_Bread)
Cookbook:Dan_Wake_(Nigerian_Bean_Dumplings)

that is if someone is interested in making a list of this book.

**Comment by hamoudak** [comment]
sorry to talk about an issue once again . some complications happend with a request to create a zim file. why I get this message repeatedly ? what to do about it .
![wp1 openzim org_ (1)](https://github.com/openzim/wp1/assets/155604457/6a248dda-b2f6-4ea2-9dc4-33125d5bec01)

**Comment by rgaudin** [comment]
Looks like a different issue. @audiodude will take a look but at first glance I'd say it's an URL encoding issue.

**Comment by audiodude** [comment]
Yes it looks like the article names are specified wrong.

Names such as:

`French_Canadian_Shepherd%27s_Pie_(Pâté_Chinois)`

have the apostrophe between `Shepherd` and `s_Pie` written in "URL encoding". However, when creating a ZIM, the mwoffliner itself attempts to percent encode the URLs before resolving them. This means that the final article that gets requested is: 

`https://en.wikibooks.org/api/rest_v1/page/html/Cookbook%3AFrench_Canadian_Shepherd%2527s_Pie_(P%C3%A2t%C3%A9_Chinois)`

Which is clearly a 404 (The `%27` became `%2527`, because the percent sign itself got encoded as `%25`).

While the proper, non 404 URL is:

`https://en.wikibooks.org/api/rest_v1/page/html/Cookbook%3AFrench_Canadian_Shepherd%27s_Pie_(P%C3%A2t%C3%A9_Chinois)`

I have filed #719 to address this issue.

Until then, you can try manually or programatiically URL decoding your list of articles so this doesn't happen.

**Comment by hamoudak** [comment]
thank you so much for your detaild reply. I have indeed tried before your answer to remove these urls, but it was the same issue, then i thought to remove more links from the top list , not specific ones and got the zim file eventually in just a minute.  not what I wanted though. as you see here I removed many links, starting after [Cookbook:Dutch Apple Fritters (Oliebollen)]  , I didn't know which links to do more about it .  anyway I appreciate your advice, and addressing this issue !

<img width="960" alt="recipes_with_images_200p-c52215185432_2024-04" src="https://github.com/openzim/wp1/assets/155604457/38f7dff2-d9a6-43a4-a40d-be2d92f27996">

**Comment by audiodude** [comment]
If you have specific Selections that are failing that you want me to look at, you can try sharing the URL on `wp1.openzim.org`. For example:

![image](https://github.com/openzim/wp1/assets/57832/e7541e4d-6b66-43c8-b70f-421a1675ac53)

And I can look more into what's happening for that specific Selection. As it is, you have dozens of selections/zim files with the same name, so it's hard for me to tell which one you're referring to specifically.

**Comment by hamoudak** [comment]
this is my list . sorry i don't know how to make this share as you did .

[cookbook_list.txt](https://github.com/openzim/wp1/files/14939706/cookbook_list.txt)

**Comment by hamoudak** [comment]
you were right , I just removed all suspicious links or unicode characters , and I got the zim file successfully .

**Comment by audiodude** [comment]
You don't have to remove the articles necessarily. If you have an article title like:

`French_Canadian_Shepherd%27s_Pie_(Pâté_Chinois)`

You can run it through something like https://www.urldecoder.io/ and get:

`French_Canadian_Shepherd's_Pie_(Pâté_Chinois)`

The latter should work.

**Comment by audiodude** [comment]
But honestly, if you have a large number of such articles, you might want to wait until I fix #719, because that will have the WP1 website do the decoding for you.

**Comment by hamoudak** [comment]
oh I got your point , I didn't know about this site , I really needed this . thank you for that.
