### ISSUE TITLE
Add Selection for Wiki Projects

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#726]
We should have a Selection tool that allows you to use a WikiProject as the source of the articles.

**Comment by audiodude** [comment]
The input could be:

- Positive list of WikiProjects to include, combined with
- Negative list of WikiProjects to exclude

The output is, of course, a selection

**Comment by Jaifroid** [comment]
I'm not sure if I'm understanding correctly, but this seems to be precisely what https://wp1.openzim.org/#/selections/wikiproject is doing?

**Comment by audiodude** [comment]
Yes that's right, we forgot to close this issue! Done.
