### ISSUE TITLE
Logs for some WikiProjects show articles getting reassessed every day

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#89]
https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/American_animation_articles_by_quality_log

The log shows the same articles, which appear to probably be every article in the project, being reassessed every day. Investigate this.

**Comment by audiodude** [comment]
https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/American_Civil_War_articles_by_quality_log

American Civil War articles seem to have the same problem.

**Comment by audiodude** [comment]
Similar problem here:

https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Adelaide_articles_by_quality_log

And this is just the A's. Looks pretty widespread.

**Comment by kelson42** [comment]
Another one https://en.wikipedia.org/w/index.php?title=Wikipedia:Version_1.0_Editorial_Team/Saints_articles_by_quality_log&oldid=913442816

**Comment by audiodude** [comment]
@walkerma if you look at the first example of this I showed, it's actually a problem with Unknown-Class it seems: https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/American_animation_articles_by_quality_log

This example also looks like a lot of problems with Unknown-Class:
https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Adelaide_articles_by_quality_log

**Comment by kelson42** [comment]
Should be fixed now
