### ISSUE TITLE
Consider putting a "no logs" message instead of just blanking the page

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#90]
For logs like this: https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Acoustics_articles_by_quality_log

It appears to an observer that we are just blanking the page. Consider putting a message like  "there are no logs for the period Aug 17-Aug 24 2019" instead.

**Comment by kelson42** [comment]
@audiodude Sounds a good idea. I propoer "No changes detected in the last few days, maybe tomorrow..."
