### ISSUE TITLE
Category:Foo moves get reported as Category:Category:Foo_moved

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#96]
See the discussion [on English Wikipedia](https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Bug_report-_moving_categories_results_in_double-namespaced_target_link) about this.

[Here's](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Video_game_articles_by_quality_log#Aug_25,_2019) an example.

Could be a problem with update or upload, either one.

**Comment by PresNCode** [comment]
Note: also seems to happen with Draft:Foo -> Draft:Draft:Foo; may be an issue with any non-mainspace (aka prefixed) page move.

**Comment by PresNCode** [comment]
Files do something a bit different: "Image:NEOGEO Spin Master (Miracle Adventure).png renamed to Image:File:NEOGEO Spinmaster (Miracle Adventure).png"
