### ISSUE TITLE
Rename repository to wp1_engine

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#97]
This code base is not only a Wikipedia bot, only 1/3 of it is. This will also be less and less the case as we will probably extend it to allow better selection/curation. Therefore, I propose to rename it to `wp1_engine`. This is only a technical part of a more broader change to better name this effort and increase awareness around the effort.

Remark: I know that "Wikipedia 1.0" is as well a name we might reconsider. I agree with the principle, but considering the difficulty of the task (nobody came so far with a convincing and consensual proposal) I propose to stick to that first.

**Comment by walkerma** [comment]
I don't have any problem with the rename to wp1_engine.  Renaming the actual WP1 project can wait for now!

**Comment by audiodude** [comment]
@kelson42 why not rename it to just /wp1 ?

**Comment by kelson42** [comment]
done
