### ISSUE TITLE
Show date headers with the full name of the month instead of the three-letter abbreviation

### ISSUE THREAD

**Issue by GeoffreyTrang** [openzim/wp1#98]
It appears that log pages like [Wikipedia:Version 1.0 Editorial Team/Years articles by quality log](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Years_articles_by_quality_log) currently show the three-letter abbreviations of the months in date headers. Previously, the full name of the month was shown. Please consider switching back to the full names of the months in date headers.

**Comment by audiodude** [comment]
Fixed by #106
