### ISSUE TITLE
Show links to images as "File:" links instead of "Image:" links

### ISSUE THREAD

**Issue by GeoffreyTrang** [openzim/wp1#99]
Links to images and their talk pages in log pages like [Wikipedia:Version 1.0 Editorial Team/Biography articles by quality log](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Biography_articles_by_quality_log) are currently shown with the "Image:" and "Image talk:" prefixes. They should instead use the "File:" and "File talk:" prefixes.

**Comment by kelson42** [comment]
@GeoffreyTrang Why? What is better with "File:"? Is that always become the naming is semantically better? or do we have additional features?

**Comment by GeoffreyTrang** [comment]
"File:" should be used because it it the current name of the namespace. If you think that "Image:" should be a separate namespace from "File:" (rather than merely an alias) in MediaWiki, then you may create a task on [Phabricator](https://phabricator.wikimedia.org/) and start an RFC seeking consensus.

**Comment by audiodude** [comment]
So I take it that at some point Image: got renamed to File: and the bot is too old and didn't get the memo.

The namespace mappings are statically stored in the application database, so this explains both why this bug survived the rewrite and how we can easily change it.

**Comment by kelson42** [comment]
> So I take it that at some point Image: got renamed to File: and the bot is too old and didn't get the memo.

Yes. There is no user impact, but would be nicer.

**Comment by audiodude** [comment]
Okay I deleted the references to "File" and "File talk" from the WP 1.0 database. I imagine this will clear this issue up, will check back tomorrow to see if it's fixed and close.

**Comment by mahakporwal02** [comment]
@audiodude Is this issue still open?

**Comment by audiodude** [comment]
I think this is fixed. I just looked at the log for [African military history](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/African_military_history_articles_by_quality_log) and it seems like images are using the `File:` prefix. Screenshot:

<img width="885" alt="Screen Shot 2021-03-18 at 7 44 56 AM" src="https://user-images.githubusercontent.com/57832/111645504-fe4d9c80-87bd-11eb-870a-0e905783347a.png">
